# Generated by Django 5.0.3 on 2024-03-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='requester_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
