# Generated by Django 5.0.3 on 2024-03-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulence', '0002_ambulance_requester_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='assigned_location_latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='assigned_location_longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='current_location_latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='current_location_longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
    ]
